apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lyeh-dev
  namespace: argocd
spec:
  description: lyeh.dev personal brand project
  sourceRepos:
    - git@github.com:LeaYeh/lyeh-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
