apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'jd-explorer'
        static_configs:
          - targets: ['jd-explorer.jd-explorer.svc.cluster.local:80']
        metrics_path: '/metrics'
